#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 4, 5
set output "full_level_set.eps"

unset border

set lmargin 0
set rmargin 1
set bmargin 0
set tmargin 4

set label "Full Data (J = 1, B = 500)" at screen 0.5, screen 0.9 center

N = 500
sigma = 2
m = 0
s = 1

full_ave = 0.946468

q0_full = (full_ave * N * s * s + m * sigma * sigma) / (sigma * sigma + N * s * s)
tau_full = sqrt( sigma * sigma * s * s / (sigma * sigma + 1.0 * N * s * s) )

E = 3
delta = sqrt(2 * E)

epsilon = 0.5
C = sqrt(1 - 0.25 * epsilon * epsilon)

set xrange [-2:5]
unset xtics

set yrange [-35:50]
unset ytics

set parametric

set trange [0: 2 * pi]

set arrow from first -2, first 0 to first 4.5, first 0 nohead lw 3 lc rgb '#CCCCCC'
set arrow from first 0, first -30 to first 0, first 30 nohead lw 3 lc rgb '#CCCCCC'

set label "q" at first 4.7, 0 center tc rgb '#CCCCCC'
set label "p" at first 0, -32 center tc rgb '#CCCCCC'

plot \
q0_full + delta * cos(t), delta * sin(t) / tau_full with lines lt 1 lc rgb '#8F278F' lw 6 title "Exact Level Set", \
q0_full + delta * cos(t), C * delta * sin(t) / tau_full with lines lt 0 lc rgb '#8F278F' lw 12 title "Modified Level Set"

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 4, 5
set output "small_batch_level_set.eps"

unset border

set lmargin 0
set rmargin 1
set bmargin 0
set tmargin 4

set label "Small Subset (J = 50, B = 10)" at screen 0.5, screen 0.9 center

B = 20
N = 500
sigma = 2
m = 0
s = 1

batch_ave = 1.71412
full_ave = 0.946468

q0 = (batch_ave * N * s * s + m * sigma * sigma) / (sigma * sigma + N * s * s)
tau = sqrt( sigma * sigma * s * s / (sigma * sigma + 1.0 * N * s * s) )

q0_full = (full_ave * N * s * s + m * sigma * sigma) / (sigma * sigma + N * s * s)
tau_full = sqrt( sigma * sigma * s * s / (sigma * sigma + 1.0 * N * s * s) )

E = 3
delta = sqrt(2 * E)

epsilon = 0.5
C = sqrt(1 - 0.25 * epsilon * epsilon)

set xrange [-2:5]
unset xtics

set yrange [-35:50]
unset ytics

set parametric

set trange [0: 2 * pi]

set arrow from first -2, first 0 to first 4.5, first 0 nohead lw 3 lc rgb '#CCCCCC'
set arrow from first 0, first -30 to first 0, first 30 nohead lw 3 lc rgb '#CCCCCC'

set label "q" at first 4.7, 0 center tc rgb '#CCCCCC'
set label "p" at first 0, -32 center tc rgb '#CCCCCC'

plot \
q0_full + delta * cos(t), delta * sin(t) / tau_full with lines lt 1 lc rgb '#8F278F' lw 6 title "Exact Level Set", \
q0_full + delta * cos(t), C * delta * sin(t) / tau_full with lines lt 0 lc rgb '#8F278F' lw 12 title "Modified Level Set", \
q0 + delta * cos(t), delta * sin(t) / tau with lines lt 1 lc rgb '#C799C7' lw 6 title "Exact Stochastic Level Set", \
q0 + delta * cos(t), C * delta * sin(t) / tau with lines lt 0 lc rgb '#C799C7' lw 12 title "Modified Stochastic Level Set"

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 4, 5
set output "large_batch_level_set.eps"

unset border

set lmargin 0
set rmargin 1
set bmargin 0
set tmargin 4

set label "Large Subset (J = 2, B = 250)" at screen 0.5, screen 0.9 center

B = 250
N = 500
sigma = 2
m = 0
s = 1

batch_ave = 1.01095
full_ave = 0.946468

q0 = (batch_ave * N * s * s + m * sigma * sigma) / (sigma * sigma + N * s * s)
tau = sqrt( sigma * sigma * s * s / (sigma * sigma + 1.0 * N * s * s) )

q0_full = (full_ave * N * s * s + m * sigma * sigma) / (sigma * sigma + N * s * s)
tau_full = sqrt( sigma * sigma * s * s / (sigma * sigma + 1.0 * N * s * s) )

E = 3
delta = sqrt(2 * E)

epsilon = 0.5
C = sqrt(1 - 0.25 * epsilon * epsilon)

set xrange [-2:5]
unset xtics

set yrange [-35:50]
unset ytics

set parametric

set trange [0: 2 * pi]

set arrow from first -2, first 0 to first 4.5, first 0 nohead lw 3 lc rgb '#CCCCCC'
set arrow from first 0, first -30 to first 0, first 30 nohead lw 3 lc rgb '#CCCCCC'

set label "q" at first 4.7, 0 center tc rgb '#CCCCCC'
set label "p" at first 0, -32 center tc rgb '#CCCCCC'

plot \
q0_full + delta * cos(t), delta * sin(t) / tau_full with lines lt 1 lc rgb '#8F278F' lw 6 title "Exact Level Set", \
q0_full + delta * cos(t), C * delta * sin(t) / tau_full with lines lt 0 lc rgb '#8F278F' lw 12 title "Modified Level Set", \
q0 + delta * cos(t), delta * sin(t) / tau with lines lt 1 lc rgb '#C799C7' lw 6 title "Exact Stochastic Level Set", \
q0 + delta * cos(t), C * delta * sin(t) / tau with lines lt 0 lc rgb '#C799C7' lw 12 title "Modified Stochastic Level Set"

END